services:
  accounts:
    image: "mjlslink5/accounts:s4"
    container_name: accounts-ms   #avoids random names
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 700M
    networks:
        - enceladus
  loans:
    image: "mjlslink5/loans:s4"
    container_name: loans-ms   #avoids random names
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 700M
    networks:
      - enceladus
  cards:
    image: "mjlslink5/cards:s4"
    container_name: cards-ms   #avoids random names
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 700M
    networks:
        - enceladus
networks:      #shared network
  enceladus:
    driver: bridge
