server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
 #this will be replacced with Kubernetes secret in real deployment
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: ''
#  h2:
#    console:
#      enabled: true
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Accounts Application"
    version: "1.0.0"

resilience4j:
  ratelimiter:
    instances:
      default:
        limit-for-period: 1
        limit-refresh-period: 10s
        timeout-duration: 0
  circuitbreaker:
    instances:
      default:
        register-health-indicator: true
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
